fix:unittest

diff --git a/.github/workflows/unittest.yml b/.github/workflows/unittest.yml
--- a/.github/workflows/unittest.yml
+++ b/.github/workflows/unittest.yml
@@ -30,6 +30,14 @@ jobs:
         pip install poetry
         poetry install
 
+    - name: download synonym file
+      run: |
+        curl -L -f -o yurenizer/data/synonyms.txt https://raw.githubusercontent.com/WorksApplications/SudachiDict/v20231220/src/main/text/synonyms.txt
+        if [ ! -f yurenizer/data/synonyms.txt ]; then
+          echo "Failed to download synonyms.txt"
+          exit 1
+        fi
+
     - name: Run tests
       run: |
         poetry run pytest
